module.exports = {
  authService: require('./auth.service'),
  userService: require('./user.service'),
  blogService: require('./blog.service'),
  projectService: require('./project.service'),
  skillService: require('./skill.service'),
  serviceService: require('./services.service'),
  testimonialService: require('./testitmonial.service'),
  educationService: require('./education.service'),
  experianceService: require('./experiance.service'),
  certificateService: require('./certificate.service'),
  faqService: require('./FAQ.service'),
  aboutService: require('./about.service'),
  navbarService: require('./navbar.service'),
  footerService: require('./footer.service'),
  messageService: require('./message.service'),
  seoService: require('./seo.service'),
  settingService: require('./setting.service'),
  socialAuthService: require('./socialAuth.service'),
};
