module.exports = {
  authController: require('./auth.controller'),
  userController: require('./user.controller'),
  blogController: require('./blog.controller'),
  projectController: require('./project.controller'),
  skillController: require('./skill.controller'),
  serviceController: require('./service.controller'),
  testimonialController: require('./testitmonial.controller'),
  educationController: require('./education.controller'),
  experianceController: require('./experiance.controller'),
  certificateController: require('./certificate.controller'),
  faqController: require('./FAQ.controller'),
  aboutController: require('./about.controller'),
  navbarController: require('./navbar.controller'),
  footerController: require('./footer.controller'),
  messageController: require('./message.controller'),
  seoController: require('./seo.controller'),
  settingsController: require('./settings.controller'),
  socialAuthController: require('./socialAuth.controller'),
};
